### ISSUE TITLE
[ASK] Sorry, not an issue, just asking. Is the cloud gaming app you created open source? and where is the repo?

### ISSUE THREAD

**Issue by azkadev** [Nika0000/nika0000#1]
I don't know if your app is made using flutter if yes that's great, I've been browsing to find out how stadia works but after seeing your project it seems great, is there a repo link? I just want a shortcut on how the app works sorry for my bad english

**Comment by Nika0000** [comment]
Hi @azkadev , Yes, the app is indeed built using Flutter, and we also leverage Dart FFI to enhance its capabilities. Unfortunately, the repository is currently private due to recent interest from investors and venture capitalists who see potential in turning it into a business. Because of this, I’m unable to share a direct link or detailed code overview at this time. However, I really hope that it will become public again in the future. If you have specific questions or need guidance on how similar features might be implemented in Flutter, I’d be happy to help out!

**Comment by azkadev** [comment]
wow amazing, actually i don't need the full source code just need the core information how can serve send data, if you don't mind which library source code you are using that has been translated to native flutter?
